import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Plus, Search, Pencil, Trash2, X } from "lucide-react";
import { createAdminProduct, deleteAdminProduct, getAdminProducts, getCategories, type CatalogProduct, type ProductInput, updateAdminProduct } from "@/lib/api/catalog";

export const Route = createFileRoute("/admin/products")({ component: ProductsAdmin });
const statuses = [{ value: 1, label: "Live" }, { value: 2, label: "Draft" }, { value: 3, label: "Out of stock" }] as const;
const money = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);
const inputClass = "w-full rounded-md border border-cream/10 bg-[#0e0c0a] px-3 py-2 text-cream outline-none focus:border-terra/50";

function ProductsAdmin() {
  const queryClient = useQueryClient(); const [q, setQ] = useState(""); const [cat, setCat] = useState("All"); const [editing, setEditing] = useState<CatalogProduct | null>(null); const [creating, setCreating] = useState(false); const [error, setError] = useState<string | null>(null);
  const products = useQuery({ queryKey: ["admin", "products"], queryFn: getAdminProducts }); const categories = useQuery({ queryKey: ["categories"], queryFn: getCategories });
  const refresh = () => {
    queryClient.invalidateQueries({ queryKey: ["admin", "products"] });
    queryClient.invalidateQueries({ queryKey: ["admin", "dashboard"] });
    queryClient.invalidateQueries({ queryKey: ["admin", "analytics"] });
  };
  const remove = useMutation({ mutationFn: deleteAdminProduct, onSuccess: refresh, onError: (e) => setError(e instanceof Error ? e.message : "Unable to delete product") });
  const list = products.data?.products ?? [];
  const filtered = useMemo(() => list.filter((p) => (cat === "All" || p.category_id === cat) && (!q || p.name.toLowerCase().includes(q.toLowerCase()) || p.sku.toLowerCase().includes(q.toLowerCase()))), [list, cat, q]);
  if (products.isPending || categories.isPending) return <div className="px-6 py-8 text-cream/55">Loading products…</div>;
  if (products.isError || categories.isError) return <div className="px-6 py-8 text-rose-300">Unable to load products. Refresh and try again.</div>;
  return <div className="space-y-6 px-6 py-8 md:px-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="font-display text-3xl">Products</h1><p className="mt-1 text-sm text-cream/55">{list.length} SKUs · {list.filter((p) => p.status === 1).length} live</p></div><button onClick={() => setCreating(true)} className="inline-flex items-center gap-2 rounded-md bg-terra px-4 py-2 text-xs uppercase tracking-[0.22em] text-umber"><Plus className="h-3.5 w-3.5" /> New product</button></div>
    {error && <p className="rounded-md border border-rose-400/30 bg-rose-500/10 px-3 py-2 text-sm text-rose-200">{error}</p>}
    <div className="flex flex-wrap items-center gap-3"><div className="flex flex-1 items-center gap-2 rounded-md border border-cream/10 bg-[#161310] px-3 py-2 text-sm"><Search className="h-4 w-4 text-cream/40" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search by name or SKU…" className="flex-1 bg-transparent text-cream outline-none" /></div><div className="flex gap-1.5 overflow-x-auto"><button onClick={() => setCat("All")} className={`rounded-md border px-3 py-1.5 text-xs uppercase tracking-[0.2em] ${cat === "All" ? "border-terra/50 bg-terra/15 text-cream" : "border-cream/10 text-cream/55"}`}>All</button>{categories.data?.categories.map((c) => <button key={c.id} onClick={() => setCat(c.id)} className={`rounded-md border px-3 py-1.5 text-xs uppercase tracking-[0.2em] ${cat === c.id ? "border-terra/50 bg-terra/15 text-cream" : "border-cream/10 text-cream/55"}`}>{c.name}</button>)}</div></div>
    <div className="overflow-hidden rounded-lg border border-cream/8 bg-[#161310]"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-cream/8 text-[10px] uppercase tracking-[0.22em] text-cream/45"><th className="px-4 py-3 text-left">Product</th><th className="px-4 py-3 text-left">SKU</th><th className="px-4 py-3 text-left">Category</th><th className="px-4 py-3 text-right">Price</th><th className="px-4 py-3 text-right">Stock</th><th className="px-4 py-3 text-left">Status</th><th /></tr></thead><tbody>{filtered.map((p) => <tr key={p.id} className="border-b border-cream/5 last:border-0"><td className="px-4 py-3"><div>{p.name}</div><div className="text-xs text-cream/45">★ {p.rating ?? "—"}</div></td><td className="px-4 py-3 text-cream/65">{p.sku}</td><td className="px-4 py-3 text-cream/65">{p.category_name}</td><td className="px-4 py-3 text-right">{money(p.price_paise)}</td><td className="px-4 py-3 text-right">{p.stock_quantity}</td><td className="px-4 py-3 text-cream/65">{statuses.find((s) => s.value === p.status)?.label}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button onClick={() => setEditing(p)} className="rounded p-1.5 text-cream/55 hover:bg-cream/10"><Pencil className="h-3.5 w-3.5" /></button><button onClick={() => remove.mutate(p.id)} disabled={remove.isPending} className="rounded p-1.5 text-cream/55 hover:bg-rose-500/15 hover:text-rose-300"><Trash2 className="h-3.5 w-3.5" /></button></div></td></tr>)}{filtered.length === 0 && <tr><td colSpan={7} className="px-4 py-12 text-center text-cream/45">No products match these filters.</td></tr>}</tbody></table></div></div>
    {(editing || creating) && <ProductDrawer initial={editing} categories={categories.data!.categories} onClose={() => { setEditing(null); setCreating(false); }} onSaved={() => { refresh(); setEditing(null); setCreating(false); }} />}</div>;
}

function ProductDrawer({ initial, categories, onClose, onSaved }: { initial: CatalogProduct | null; categories: { id: string; name: string }[]; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<ProductInput>(initial ? { category_id: initial.category_id, sku: initial.sku, slug: initial.slug, name: initial.name, description: initial.description, price_paise: initial.price_paise, original_price_paise: initial.original_price_paise, stock_quantity: initial.stock_quantity, status: initial.status, rating: initial.rating, image_url: initial.image_url } : { category_id: categories[0]?.id ?? "", sku: "", slug: "", name: "", description: "", price_paise: 0, original_price_paise: null, stock_quantity: 0, status: 2, rating: null, image_url: null });
  const mutation = useMutation({ mutationFn: () => initial ? updateAdminProduct(initial.id, form) : createAdminProduct(form), onSuccess: onSaved });
  const set = <K extends keyof ProductInput>(key: K, value: ProductInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/50" onClick={onClose}><div className="h-full w-full max-w-md overflow-y-auto border-l border-cream/10 bg-[#161310] p-6" onClick={(e) => e.stopPropagation()}><div className="flex justify-between"><div><div className="text-[10px] uppercase tracking-[0.28em] text-cream/45">{initial ? "Edit" : "Create"}</div><h2 className="mt-1 font-display text-2xl">{initial ? form.name : "New product"}</h2></div><button onClick={onClose}><X /></button></div><div className="mt-6 space-y-4 text-sm"><Field label="Name"><input value={form.name} onChange={(e) => set("name", e.target.value)} className={inputClass} /></Field><Field label="Description"><textarea value={form.description} onChange={(e) => set("description", e.target.value)} className={inputClass} /></Field><div className="grid grid-cols-2 gap-3"><Field label="SKU"><input value={form.sku} onChange={(e) => set("sku", e.target.value)} className={inputClass} /></Field><Field label="Slug"><input value={form.slug} onChange={(e) => set("slug", e.target.value)} className={inputClass} /></Field></div><Field label="Category"><select value={form.category_id} onChange={(e) => set("category_id", e.target.value)} className={inputClass}>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Price (paise)"><input type="number" value={form.price_paise} onChange={(e) => set("price_paise", Number(e.target.value))} className={inputClass} /></Field><Field label="Stock"><input type="number" value={form.stock_quantity} onChange={(e) => set("stock_quantity", Number(e.target.value))} className={inputClass} /></Field></div><Field label="Status"><select value={form.status} onChange={(e) => set("status", Number(e.target.value) as 1 | 2 | 3)} className={inputClass}>{statuses.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}</select></Field><Field label="Image URL"><input value={form.image_url ?? ""} onChange={(e) => set("image_url", e.target.value || null)} className={inputClass} /></Field>{mutation.isError && <p className="text-rose-300">{mutation.error.message}</p>}</div><div className="mt-8 flex gap-3"><button disabled={mutation.isPending} onClick={() => mutation.mutate()} className="flex-1 rounded-md bg-terra px-4 py-2.5 text-xs uppercase tracking-[0.22em] text-umber">Save product</button><button onClick={onClose} className="rounded-md border border-cream/15 px-4 py-2.5 text-xs uppercase tracking-[0.22em] text-cream/70">Cancel</button></div></div></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[10px] uppercase tracking-[0.22em] text-cream/45">{label}</span>{children}</label>; }
