import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { createCategory, deleteCategory, getCategories, type Category, updateCategory } from "@/lib/api/catalog";

export const Route = createFileRoute("/admin/categories")({ component: CategoriesPage });
function CategoriesPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["categories"], queryFn: getCategories }); const [editing, setEditing] = useState<Category | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const refresh = () => {
    client.invalidateQueries({ queryKey: ["categories"] });
    client.invalidateQueries({ queryKey: ["admin", "products"] });
    client.invalidateQueries({ queryKey: ["admin", "dashboard"] });
    client.invalidateQueries({ queryKey: ["admin", "analytics"] });
  };
  const remove = useMutation({ mutationFn: deleteCategory, onSuccess: refresh, onError: (e) => setNotice(e instanceof Error ? e.message : "Unable to delete category") });
  if (query.isPending) return <div className="px-6 py-8 text-cream/55">Loading categories…</div>; if (query.isError) return <div className="px-6 py-8 text-rose-300">Unable to load categories.</div>;
  return <div className="space-y-6 px-6 py-8 md:px-10"><div className="flex items-center justify-between"><div><h1 className="font-display text-3xl">Categories</h1><p className="mt-1 text-sm text-cream/55">Organize the apothecary.</p></div><button onClick={() => setEditing({ id: "", name: "", slug: "" })} className="rounded-md bg-terra px-4 py-2 text-xs uppercase tracking-[.22em] text-umber">New category</button></div>{notice && <p className="text-rose-300">{notice}</p>}<div className="overflow-hidden rounded-lg border border-cream/8 bg-[#161310]"><table className="w-full text-sm"><thead><tr className="border-b border-cream/8 text-left text-[10px] uppercase tracking-[.22em] text-cream/45"><th className="px-4 py-3">Name</th><th className="px-4 py-3">Slug</th><th /></tr></thead><tbody>{query.data?.categories.map((c) => <tr key={c.id} className="border-b border-cream/5"><td className="px-4 py-3">{c.name}</td><td className="px-4 py-3 text-cream/55">{c.slug}</td><td className="px-4 py-3 text-right"><button onClick={() => setEditing(c)} className="mr-3 text-terra">Edit</button><button disabled={remove.isPending} onClick={() => remove.mutate(c.id)} className="text-rose-300">Delete</button></td></tr>)}{!query.data?.categories.length && <tr><td colSpan={3} className="px-4 py-12 text-center text-cream/45">No categories yet.</td></tr>}</tbody></table></div>{editing && <CategoryForm initial={editing} close={() => setEditing(null)} saved={() => { refresh(); setEditing(null); }} />}</div>;
}
function CategoryForm({ initial, close, saved }: { initial: Category; close: () => void; saved: () => void }) { const [name, setName] = useState(initial.name); const [slug, setSlug] = useState(initial.slug); const mutation = useMutation({ mutationFn: () => initial.id ? updateCategory(initial.id, { name, slug }) : createCategory({ name, slug }), onSuccess: saved }); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"><div className="w-full max-w-md rounded-lg bg-[#161310] p-6"><h2 className="font-display text-2xl">{initial.id ? "Edit category" : "New category"}</h2><label className="mt-5 block text-sm">Name<input value={name} onChange={(e) => setName(e.target.value)} className="mt-1 w-full rounded border border-cream/10 bg-[#0e0c0a] p-2" /></label><label className="mt-4 block text-sm">Slug<input value={slug} onChange={(e) => setSlug(e.target.value)} className="mt-1 w-full rounded border border-cream/10 bg-[#0e0c0a] p-2" /></label>{mutation.isError && <p className="mt-3 text-rose-300">{mutation.error.message}</p>}<div className="mt-6 flex gap-3"><button disabled={mutation.isPending} onClick={() => mutation.mutate()} className="rounded bg-terra px-4 py-2 text-umber">Save</button><button onClick={close}>Cancel</button></div></div></div>; }
