import type { Request, Response } from "express";
import { db } from "../db/pool.js";

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const addressColumns = "id, label, address_line1, address_line2, city, state, postal_code, country, phone";
function object(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function value(input: unknown, min = 1, max = 255): string | null { if (typeof input !== "string") return null; const result = input.trim().replace(/\s+/g, " "); return result.length >= min && result.length <= max ? result : null; }
function address(body: unknown): string[] | null { if (!object(body)) return null; const line2 = body.address_line2 == null || body.address_line2 === "" ? null : value(body.address_line2); const fields = [value(body.label, 1, 100),value(body.address_line1),line2,value(body.city, 1, 100),value(body.state, 1, 100),value(body.postal_code, 1, 30),value(body.country, 1, 100),value(body.phone, 1, 30)]; const required = [fields[0], fields[1], fields[3], fields[4], fields[5], fields[6], fields[7]]; return required.every((field) => field !== null) ? fields as string[] : null; }

export function getProfile(request: Request, response: Response): void { response.json({ user: request.authUser }); }
export async function updateProfile(request: Request, response: Response): Promise<void> { const name = object(request.body) ? value(request.body.name, 2, 255) : null; if (!name) { response.status(400).json({ error: "Name must be between 2 and 255 characters" }); return; } const result = await db.query("UPDATE users SET name = $1, updated_at = NOW() WHERE id = $2 RETURNING id, name, email, role", [name, request.authUser!.id]); response.json({ user: result.rows[0] }); }
export async function listAddresses(request: Request, response: Response): Promise<void> { const result = await db.query(`SELECT ${addressColumns} FROM addresses WHERE user_id = $1 ORDER BY created_at DESC`, [request.authUser!.id]); response.json({ addresses: result.rows }); }
export async function createAddress(request: Request, response: Response): Promise<void> { const fields = address(request.body); if (!fields) { response.status(400).json({ error: "All required address fields must be valid" }); return; } const result = await db.query(`INSERT INTO addresses (user_id,label,address_line1,address_line2,city,state,postal_code,country,phone) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING ${addressColumns}`, [request.authUser!.id,...fields]); response.status(201).json({ address: result.rows[0] }); }
export async function updateAddress(request: Request<{ id: string }>, response: Response): Promise<void> { if (!uuid.test(request.params.id)) { response.status(400).json({ error: "Invalid address id" }); return; } const fields = address(request.body); if (!fields) { response.status(400).json({ error: "All required address fields must be valid" }); return; } const result = await db.query(`UPDATE addresses SET label=$1,address_line1=$2,address_line2=$3,city=$4,state=$5,postal_code=$6,country=$7,phone=$8,updated_at=NOW() WHERE id=$9 AND user_id=$10 RETURNING ${addressColumns}`, [...fields,request.params.id,request.authUser!.id]); if (!result.rows[0]) response.status(404).json({ error: "Address not found" }); else response.json({ address: result.rows[0] }); }
export async function deleteAddress(request: Request<{ id: string }>, response: Response): Promise<void> { if (!uuid.test(request.params.id)) { response.status(400).json({ error: "Invalid address id" }); return; } const result = await db.query("DELETE FROM addresses WHERE id = $1 AND user_id = $2", [request.params.id,request.authUser!.id]); if (!result.rowCount) response.status(404).json({ error: "Address not found" }); else response.sendStatus(204); }
